import React from "react";
import {
  makeStyles,
  createStyles,
} from "@mui/styles";
import { Theme } from "@mui/material/styles";
import Head from "next/head";
import { Typography, Link, Box, styled } from "@mui/material";
import Tooltip, { tooltipClasses, TooltipProps } from "@mui/material/Tooltip";
import HomePage from '../components/homePage';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      flexGrow: 1,
      marginTop: 10,
    },
    headingBlock: {
      background: "#007070",
      width: "100%",
      padding: 20,
      color: "#fff",
      display: "flex",
      flexDirection: "row",
    },
    infoHeading: {
      color: "#444444",
      padding: "8px",
    },
    infoText: {
      color: "#7A7A7A",
      fontSize: "12px",
      lineHeight: "19.2px",
      padding: "8px",
    },
    infoLearnMore: {
      color: "#7A7A7A",
      fontSize: "12px",
      lineHeight: "19.2px",
      padding: "8px",
    },
    infoClearText: {
      color: "grey",
      textDecoration: "underline",
      paddingLeft: 10,
      fontSize: 15,
    },
    line: {
      height: 1,
      background: "#F1F1F1",
      border: "none",
    },
    infoBottom: {
      display: "flex",
      flexDirection: "row",
      marginTop: 10,
    },
    infoBottomText: {
      color: "#444444",
      textDecoration: "underline",
      marginTop: 4,
    },
    displayMessage: {
      display: "flex",
      justifyContent: "center",
      height: "100vh",
      alignItems: "center",
      color: "#A4A4A4",
    },
    link: {
      color: "#404141",
    },
  })
);

const BootstrapTooltip = styled(({ className, ...props }: TooltipProps) => (
  <Tooltip {...props} arrow classes={{ popper: className }} placement="right" />
))(({ theme }) => ({
  [`& .${tooltipClasses.arrow}`]: {
    color: theme.palette.common.white,
    "&:before": {
      border: "2px solid #C4C4C4",
    },
  },
  [`& .${tooltipClasses.tooltip}`]: {
    backgroundColor: theme.palette.common.white,
    color: theme.palette.common.black,
    fontSize: 30,
    border: "2px solid #C4C4C4",
  },
}));

const StartWrapper = styled('div')(
  ({ theme }) => `
    background: #007070;
    width: 100%;
    padding: 20px;
    color: #fff;
    display: flex;
    flexDirection: row;
  `,
);

const MainContent = styled('div')(
  ({ theme }) => `
  flex-grow: 1;
  margin-top: 10;
  `,
);

export default function Home() {
  const classes = useStyles();

  return (
    <div>
      <Head>
        <title>SDET Testing Implementation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContent>
        <StartWrapper>
          <Typography variant="h5" component="h1">
              SDET Test
            </Typography>
          </StartWrapper>
        <HomePage/>
      </MainContent>
    </div>
  );
}
